mongodb:
  address: "localhost"
  port: 27017
  database: "survival"
  authentication:
    enabled: false
    username: "root"
    password: "******"

redis:
  address: "localhost"
  port: 6379
  password: ""

rank-ups:
  default:
    prefix: "&fNoob"
  diamond:
    time: 7 #In Days
    prefix: "&b&lDiamond"
    commands:
      - "lp user <player> parent set diamond"

commands:
  see:
    next:
      - "&7&m&l----------------------------"
      - "&7Te falta &b<parsedTime> &7para"
      - "&7obtener el rango <newRankPrefix>"
      - "&7&m&l----------------------------"
    no-more:
      - "&7&m&l----------------------------"
      - "&7You're in the last rankup."
      - "&7&m&l----------------------------"
  listed:
    format: "&7<rankPrefix> &8- &b<rankPendingTime>&7/&b<rankNeededTime>"
    format-already: "&7<rankPrefix> &8- &b&b<rankNeededTime> &7(obtenido)"
    send:
      - "&7&m&l----------------------------"
      - "&7Rank list:"
      - "<ranks>"
      - "&7&m&l----------------------------"

ranked:
  all:
    - "&7&m&l----------------------------"
    - "&b<player> &7rankup to &b<rankPrefix>&7!"
    - "&7&m&l----------------------------"
  own:
    - "&7&m&l----------------------------"
    - "&7You rankup to &b<rankPrefix>&7!"
    - "&7&m&l----------------------------"

shop-items:
  golden-apple:
    item:
      display-name: "&6&lGolden Apple &7($500)"
      material: "GOLDEN_APPLE"
      data: 0
      amount: 64
      glow: false
      description:
        - "&fSale a 500 perry"
    price: 500
    commands:
      - "give <player> GOLDEN_APPLE 1"