main: online.nasgar.survival.Survival
name: SurvivalCore
author: Nasgar Development Team
version: ${project.version}
api-version: 1.13

depend: [Vault, TimedRankup, PlaceholderAPI]
softdepend:
  - Luckperms