main: online.nasgar.survival.Survival
name: SurvivalCore
author: Nasgar Development Team
version: ${project.version}
api-version: 1.13

loadbefore:
  - TimedRankup
  - Vault
depend:
  - TimedRankup
  - PlaceholderAPI
  - Vault
softdepend:
  - Luckperms