author: Nasgar Development Team
name: SurvivalCore
main: online.nasgar.survival.Survival
version: ${project.version}
api-version: 1.13

loadbefore:
  - TimedRankup
depend:
  - TimedRankup
  - PlaceholderAPI
softdepend:
  - Luckperms